apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: muchtodo
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: muchtodousr
  MONGO_INITDB_ROOT_PASSWORD: "Password!234"
  MONGO_URI: "mongodb://muchtodousr:Password!234@mongodb-service:27017/much_todo_db?authSource=admin&directConnection=true"
